spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /main

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: debug

#server:
#  servlet:
#    context-path: /sk

